//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test_OnlineEntities1 : DbContext
    {
        public Test_OnlineEntities1()
            : base("name=Test_OnlineEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KELOMPOK_SOAL> KELOMPOK_SOAL { get; set; }
        public virtual DbSet<PESERTA> PESERTA { get; set; }
        public virtual DbSet<PESERTA_JAWABAN_DETAIL> PESERTA_JAWABAN_DETAIL { get; set; }
        public virtual DbSet<PESERTA_TES> PESERTA_TES { get; set; }
        public virtual DbSet<PILIHAN_JAWABAN> PILIHAN_JAWABAN { get; set; }
        public virtual DbSet<PROFIL_PESERTA> PROFIL_PESERTA { get; set; }
        public virtual DbSet<SOAL> SOAL { get; set; }
        public virtual DbSet<SUBTES> SUBTES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TES> TES { get; set; }
        public virtual DbSet<TIPE_SOAL> TIPE_SOAL { get; set; }
        public virtual DbSet<WILAYAH> WILAYAH { get; set; }
    }
}
