//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBTES()
        {
            this.SOAL = new HashSet<SOAL>();
        }
    
        public int ID_SUBTES { get; set; }
        public Nullable<int> ID_TES { get; set; }
        public Nullable<System.TimeSpan> DURASI_SUB { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string NAMA_SUBTES { get; set; }
    
        public virtual TES TES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOAL> SOAL { get; set; }
    }
}
